# Generated by Django 4.2 on 2026-01-30 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_kategori_id_alter_product_status_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='kategori_id',
            new_name='kategori',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='status_id',
            new_name='status',
        ),
    ]
